### ISSUE TITLE
Additional nltk dependency- stopwords

### ISSUE THREAD

**Issue by ForensicITGuy** [mitre-attack/tram#1]
When installing and running TRAM for the first time there is an additional step that needs to occur:

Execute the Python console and execute:

```
import nltk
nltk.download('stopwords')
```

This is really quick, simple and can be included in the documentation under the nltk download of punkt.

**Comment by javalireports** [comment]
you are right, after downloading stopwords analyse page worked for me.

**Comment by connormagee** [comment]
The README has been updated to include the stopwords nltk package!
