### ISSUE TITLE
"Add A Missing Technique" Dropdown List Doens't Fit the Div

### ISSUE THREAD

**Issue by pe3zx** [mitre-attack/tram#12]
Tested on af3b1acaa73 with Chrome Version 79.0.3945.88 (Official Build) (64-bit). The dropdown list on "Add A Missing Technique" is larger than the Div, causing some texts hidden.

![2020-01-03_17-26-58](https://user-images.githubusercontent.com/2124448/71718861-266a0d80-2e4f-11ea-8b70-a59a991c4764.png)

**Comment by strannies** [comment]
Fixed in PR #25 . Techniques are now left hugging (front of word) and for those that are longer users can scroll to read.
