### ISSUE TITLE
Blank report after submitting

### ISSUE THREAD

**Issue by Cr4ck3nCV** [mitre-attack/tram#17]
After submitting a new url the review is empty, however source button has content (url submitted) and when i click Analyze button retorned '404: Not Found'.
Not sure if i've missed something or it's something that have not been implemented.

URL tested: https://www.fireeye.com/blog/threat-research/2017/12/targeted-attack-in-middle-east-by-apt34.html

![Captura](https://user-images.githubusercontent.com/40208580/71989972-e631d300-3232-11ea-8701-01229253ed9e.PNG)

**Comment by connormagee** [comment]
I just ran the report myself and was able to find some techniques. 1) Are you behind a proxy that might not allow TRAM to reach out to the internet? 2) Are there any other error messages besides the 404? 3) Try deleting the database and rebuilding

**Comment by Cr4ck3nCV** [comment]
Hi connor,

I've checked your advices but with no success.

Log status:
INFO:aiohttp.access:127.0.0.1 [09/Jan/2020:08:07:11 +0000] "POST /rest HTTP/1.1" 200 160 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
INFO:aiohttp.access:127.0.0.1 [09/Jan/2020:08:08:01 +0000] "GET / HTTP/1.1" 200 10192 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
INFO:aiohttp.access:127.0.0.1 [09/Jan/2020:08:08:01 +0000] "GET /theme/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 200 18249 "http://localhost:9999/theme/style/bootstrap-glyphicon.min.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
INFO:aiohttp.access:127.0.0.1 [09/Jan/2020:08:08:05 +0000] "GET /edit/ HTTP/1.1" 404 172 "http://localhost:9999/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
INFO:aiohttp.access:127.0.0.1 [09/Jan/2020:08:08:05 +0000] "GET /favicon.ico HTTP/1.1" 404 172 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
![Captura](https://user-images.githubusercontent.com/40208580/72049785-f0e67980-32bf-11ea-8c84-5f44cef7cc21.PNG)

Screenshot: Attached.

PS: Database has deleted and created again

**Comment by Cr4ck3nCV** [comment]
Seems something goes wrong after loading a model template...

[#] Loading models from pickled file: model_dict.p
/home/pijachu/.local/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.21.1 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/home/pijachu/.local/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.linear_model.logistic module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.linear_model. Anything that cannot be imported from sklearn.linear_model is now part of the private API.
  warnings.warn(message, FutureWarning)
/home/pijachu/.local/lib/python3.6/site-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator LogisticRegression from version 0.21.1 when using version 0.22. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

**Comment by Cr4ck3nCV** [comment]
Tested in Windows environment with same result

**Comment by Cr4ck3nCV** [comment]
Some errors fixed with 0.21.1 version scikit-learn for the model. 

To do that:
pip uninstall scikit-learn
pip install -v scikit-learn==0.21.1

However, the issue still persists

**Comment by sarahyoder** [comment]
Have you checked the current DB and ensured there is data in there? in a terminal go to the database directory and try:
`sqlite3 tram.db`
`select * from attack_uids;`

**Comment by Cr4ck3nCV** [comment]
Hi Sarah,

Table attack_uids:
630 rows
 (screenshot attached)

![Captura](https://user-images.githubusercontent.com/40208580/72075283-b4cd0c00-32f3-11ea-825b-7c5a701d4bc5.PNG)

Table reports:
4 rows 
 (screenshot attached)
![Captura](https://user-images.githubusercontent.com/40208580/72075538-3b81e900-32f4-11ea-8e64-5a048c7b2bee.PNG)

It doesn't seem to be the database..

**Comment by sarahyoder** [comment]
I think I have tracked down the root of the problem, I believe it was not well communicated that there was a update to the database schema, so it needs to be rebuilt. Try deleting the tram.db file and starting the program again. We will be adding in line database upgrades in the future.

**Comment by Cr4ck3nCV** [comment]
Hi Sarah,

I've just rebuilt the database but the problem still persist.

![image](https://user-images.githubusercontent.com/40208580/72518964-bbf59c00-3856-11ea-9071-45db8591d656.png)
![image](https://user-images.githubusercontent.com/40208580/72518978-c44dd700-3856-11ea-842d-73ab4eb897c6.png)
![image](https://user-images.githubusercontent.com/40208580/72518994-cb74e500-3856-11ea-8df8-cb49388ef094.png)

Anyway, thank you very much for your help.

**Comment by chubbymaggie** [comment]
@Cr4ck3nCV I faced similar issue.
to solve, you need to give `title` and don't leave that empty :)

because `analyze` uses title as part of its endpoint:
e.g., title: test 
report: http://localhost:9999/edit/test

**Comment by Cr4ck3nCV** [comment]
> @Cr4ck3nCV I faced similar issue.
> to solve, you need to give `title` and don't leave that field empty :)
> 
> because `analyze` uses title as part of its endpoint:
> e.g., title: `test`
> report: http://localhost:9999/edit/test

Fixed! If the title is empty it doesn't work.  Thank you @chubbymaggie
