### ISSUE TITLE
Update ATT&CK™ to ATT&CK®

### ISSUE THREAD

**Issue by isaisabel** [mitre-attack/tram#22]
# **Please Describe The Problem To Be Solved**

ATT&CK is now a registered trademark and the documentation and UI for TRAM should reflect this.

# *Proposed Change*

- All instances of ATT&CK™ should be replaced with ATT&CK®. See also https://github.com/mitre-attack/attack-website/issues/55
- Update trademark description to `MITRE ATT&CK and ATT&CK are registered trademarks of The MITRE Corporation` anywhere it may occur. See also https://github.com/mitre-attack/attack-website/issues/54.
- Update wordmarks (logos) to ATT&CK® anywhere they may occur. See also https://github.com/mitre-attack/attack-website/issues/56.
- Copyrights should be updated to 2020. See also https://github.com/mitre-attack/attack-website/issues/58.
- Update ATT&CK™ to ATT&CK® in the README. See also https://github.com/mitre-attack/attack-website/issues/59.

Note: some of the above may be irrelevant, I haven't looked at your UI in a while. I'm just trying to get the trademark changes standardized across the infrastructure.

**Comment by strannies** [comment]
Fixed in PR #25
