### ISSUE TITLE
Newspaper library bug in TRAM

### ISSUE THREAD

**Issue by ForensicITGuy** [mitre-attack/tram#29]
# **Please Describe The Bug**

There is a bug in TRAM related to the newspaper Python library. During the download and parsing of some articles, no text is retrieved and parsed. This is a known issue with the newspaper library as shown here: https://github.com/codelucas/newspaper/issues/646

This requires either a workaround or an update of the library after it gets fixed.

**Comment by shashank7596** [comment]
Hello @ForensicITGuy  Is this issue fixed. If so please can you let me now where's the fix. I was not able to find any info regarding this I posted my comments https://github.com/codelucas/newspaper/issues/646#issuecomment-604419121

Thanks.

**Comment by ForensicITGuy** [comment]
Hi @shashank7596, to my knowledge the issue hasn't been fixed (yet). The MITRE folks have visibility to the issue so it's something they're definitely aware of. I'm not sure of the visibility of the bug inside the larger `newspaper` project.

**Comment by markeaimark** [comment]
We have been working on a major refactor which ends the use of the newspaper library. That should remove this issue from occurring.
