### ISSUE TITLE
if no title given, it runs but you can't link/edit

### ISSUE THREAD

**Issue by paralax** [mitre-attack/tram#55]
summary: if you don't have a title for your link, you can't edit the output. 

suggestion: enforce a title on submission, or auto-generate a value. 

# **Please Describe The Bug**

i have TRAM running in a docker, database gets built etc. but then i had some problems getting URLs and titles added, so i just added a URL. it ran and wound up in the "needs review" state, and i could see it in the database but it had no valid "review" link. it looked like this:

```
>>> cur.execute("SELECT * FROM reports").fetchall()
[(2, '', 'https://www.fireeye.com/blog/threat-research/2020/04/excelerating-analysis-lookup-pivot.html', None, 'needs_review')]
```

when i added a title it was fine, i could review etc as expected. 

thanks for TRAM, when i sidestep this bug it works well and i appreciate it.

**Comment by markeaimark** [comment]
Hi @paralax we have been working very hard on a major refactor, which includes a fix to this issue. Stay tuned for that release.

**Comment by paralax** [comment]
oh cool, glad to hear. feel free to close this issue, then, as you and your team deem appropriate. thank you.
