### ISSUE TITLE
requirements issues - unused jieba3k ?

### ISSUE THREAD

**Issue by wesinator** [mitre-attack/tram#58]
# **Please Describe The Bug**

- I can't find where jieba3k is used in this project
If it's a dependency of another dependency, pip can resolve the dependency automatically.

Also there seems to be a newer package of whatever "jieba" is at https://github.com/fxsjy/jieba 

 - Why do are the requirements all require specific versions ? Some of them are behind, and forcing a specific version increases the likelihood of breaking dependencies for other packages

IMO this is only safe to run in a virtualenv in its current state

**Comment by MarkDavidson** [comment]
Hello @wesinator  and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and the bug has been fixed in that repository so I am closing this issue. Thank you!
