### ISSUE TITLE
LookupError requiring NLTK Download of punkt

### ISSUE THREAD

**Issue by gren-bean** [mitre-attack/tram#62]
Posting in case you would like to update install instructions

### Solution

Download punkt package per instructions here:
https://stackoverflow.com/questions/4867197/failed-loading-english-pickle-with-nltk-data-load

### ERROR Message this resolves

LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

**Comment by gren-bean** [comment]
I realize now that **jecarr** addresses this as part of his solution in Issue #59.

Implementing the ntlk download and also the changes in Pull #61 allowed me to run server. I'm going to close this issue since it should be addressed by implementing suggestions / changes jecarr mentions in Issues #59

**Comment by jecarr** [comment]
No worries! Credit to 2xyo for PR #49 for raising this too

PS.

> I realize now that **jecarr** addresses this as part of **his** solution in Issue #59.

***her** solution 😉
