### ISSUE TITLE
Support for ATT&CK sub-techniques

### ISSUE THREAD

**Issue by rubinatorz** [mitre-attack/tram#64]
# **Please Describe The Problem To Be Solved**

July 8 MITRE released the sub-techniques version of ATT&CK. I would like to know when TRAM is going to support this sub-techniques release. I now need to run TRAM with "taxii-local: local-json" in the config file providing an old version of the STIX objects. It would be great to run TRAM against the online TAXII server and also to have support for mapping threat intelligence to sub-techniques.

# *Proposed Change*

Support for sub-techniques.

**Comment by rkzhang95** [comment]
same question

**Comment by MarkDavidson** [comment]
Hello @rubinatorz and thank you for the feature request! TRAM has moved to https://github.com/center-for-threat-informed-defense/tram/ and supports the subtechnique update of ATT&CK, so I am closing this issue.

Thank you!

**Comment by rubinatorz** [comment]
Yeah, I saw it! That's great!
