### ISSUE TITLE
Error while running requirements.txt

### ISSUE THREAD

**Issue by Aksh97** [mitre-attack/tram#66]
**ERROR: lightgbm 3.0.0 has requirement scikit-learn!=0.22.0, but you'll have scik
it-learn 0.22 which is incompatible.**
Installing collected packages: PyYAML, scipy, scikit-learn, simplejson, stix2-pa
tterns, stix2, taxii2-client, urllib3
  Found existing installation: PyYAML 5.1.1
**ERROR: Cannot uninstall 'PyYAML'. It is a distutils installed project and thus w
e cannot accurately determine which files belong to it which would lead to only
a partial uninstall.**

Found this error while installing requirements.txt

**Comment by HugooB** [comment]
It's not related this project, but you could try to follow the steps mentioned in this issue:

https://github.com/pypa/pip/issues/5247#issuecomment-410910018

**Comment by MarkDavidson** [comment]
Hello @Aksh97 and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and the bug has been fixed in that repository so I am closing this issue. Thank you!
