### ISSUE TITLE
getting  aiohttp error during pip install

### ISSUE THREAD

**Issue by ssfd7** [mitre-attack/tram#78]
ERROR: Could not find a version that satisfies the requirement aiohttp==3.6.2 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for aiohttp==3.6.2 (from -r requirements.txt (line 1))
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

- Any idea?

**Comment by jecarr** [comment]
Hey @ssfd7 - what OS are you using? Are any solutions [here](https://stackoverflow.com/questions/45954528) helpful?

**Comment by MarkDavidson** [comment]
Hello @ssfd7 and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and this issue is no longer present in that repository so I am closing this issue. Thank you!
