### ISSUE TITLE
Enforce Unique titles

### ISSUE THREAD

**Issue by jecarr** [mitre-attack/tram#82]
### **Please Describe The Problem To Be Solved**

Minor but it would be a nice tweak to enforce unique titles. Currently, if you have two submissions with the same title and they both reach 'Needs Review', you can't select the second report.

### *Proposed Change*

I have a fix here - arachne-threat-intel/thread@ba5dbc3 - but haven't created a PR due to maintaining #61. The approach is designed based on saving a file with an existing filename and 'filename_X' versions.

**Comment by MarkDavidson** [comment]
Hello @jecarr and thank you for the enhancement request. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and this is implemented in that repository so I am closing this issue. Thank you!
