### ISSUE TITLE
Include missing report text

### ISSUE THREAD

**Issue by jecarr** [mitre-attack/tram#83]
### **Please Describe The Problem To Be Solved**

Some articles have missing text after they have been processed and left the queue. (Example [url](https://www.wired.com/story/russias-fancy-bear-hackers-are-hitting-us-campaign-targets-again/).)

### *Proposed Change*

This is partly due to newspaper's approach on selecting the best html element to represent a page. (I have a PR here for newspaper-specific changes: codelucas/newspaper#885.)

Another reason is the web service's `_extract_html_as_list()` method which assumes every line in the html finishes with a `\n` character. This makes the `forward_advancer` susceptible to moving past a line in the method `map_all_html()` therefore omitting the line in the final parsed report.

I have a fix here - arachne-threat-intel/thread@408af5f* - but haven't created a PR due to maintaining #61. The approach is a re-write of building the html-text-list based on how newspaper built the html.

*Edit: 
Updated in commit arachne-threat-intel/thread@59b20ce; updates:
  - `etree.fromstring()` can break when broken html is passed; replaced method usage
  - Made text matching in `map_all_html()` easier  

Updated in commit arachne-threat-intel/thread@f6b3256; updates:
  - IndexErrors from previous commit fixed in `map_all_html()`
  - Ignore logging in rest_svc -> if wanted, `report_id` must be surrounded by str() 

Updated in commit arachne-threat-intel/thread@6e54e1a; updates:
  - IndexErrors still persisted in `map_all_html()`; removed my initial code that caused this

**Comment by MarkDavidson** [comment]
Hello @jecarr and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and I believe this issue is no longer present in that repository so I am closing this issue. Thank you!
