### ISSUE TITLE
Pip install Requirements fails

### ISSUE THREAD

**Issue by Lex1020** [mitre-attack/tram#84]
I've tried installing TRAM on several different system now including Ubuntu 20.04, Kali 20.02, and Windows 10 1903.  

All of them have failed with the pip install requirements.  This is the log from the Ubuntu install 

```
Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpt934jn34_in_process.py prepare_metadata_for_build_wheel /tmp/tmpijjsktyz
         cwd: /tmp/pip-install-ob8gwwpl/scipy_27ad46ece2984d79b2b88fc31ea9f881
    Complete output (155 lines):
    setup.py:386: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-6wzxcru3'), proceeding with generating Cython sources and expanding templates
      warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
    Running from scipy source directory.
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
```
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    flame_info:
    customize UnixCCompiler
      libraries flame not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib64
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib64
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib64
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    accelerate_info:
      NOT AVAILABLE
    
    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE
    
    /tmp/pip-build-env-0wrkyynf/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
    lapack_src_info:
      NOT AVAILABLE
    
    /tmp/pip-build-env-0wrkyynf/overlay/lib/python3.9/site-packages/numpy/distutils/system_info.py:1712: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      if getattr(self, '_calc_info_{}'.format(lapack))():
      NOT AVAILABLE
    
    Traceback (most recent call last):
      File "/tmp/tmpt934jn34_in_process.py", line 280, in <module>
        main()
      File "/tmp/tmpt934jn34_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpt934jn34_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-0wrkyynf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 166, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-0wrkyynf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 258, in run_setup
        super(_BuildMetaLegacyBackend,
      File "/tmp/pip-build-env-0wrkyynf/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 150, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 505, in <module>
        setup_package()
      File "setup.py", line 501, in setup_package
        setup(**metadata)
      File "/tmp/pip-build-env-0wrkyynf/overlay/lib/python3.9/site-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "setup.py", line 403, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.

```
WARNING: Discarding https://files.pythonhosted.org/packages/a7/5c/495190b8c7cc71977c3d3fafe788d99d43eeb4740ac56856095df6a23fbd/scipy-1.3.3.tar.gz#sha256=64bf4e8ae0db2d42b58477817f648d81e77f0b381d0ea4427385bba3f959380a (from https://pypi.org/simple/scipy/) (requires-python:>=3.5). Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpt934jn34_in_process.py prepare_metadata_for_build_wheel /tmp/tmpijjsktyz Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement scipy==1.3.3
ERROR: No matching distribution found for scipy==1.3.3
```

**Comment by jecarr** [comment]
Hi @Lex1020, sorry to hear about the errors. I similarly went through a lot of errors whilst upgrading to Python 3.9.

I was able to replicate your stack trace. At the time of my errors, changing these versions in requirements.txt enabled me to complete installation:
```
aiohttp==3.7.3
lxml==4.6.2
multidict==5.1.0
numpy==1.20.1
pandas==1.2.2
Pillow==8.1.0
scikit-learn==0.24.1
scipy==1.6.0
yarl==1.6.3
```
What would be better is installing the latest version of each dependency causing you an error (so your first one is `scipy` given your stack trace). This is because the versions I've listed above were the latest at the time of my upgrade to Python 3.9 and some now have updates available. Understandably, this can be time consuming (dealing with error after error) so I get it if you just want to use the versions above.

Furthermore, with the new versions you may encounter errors. Please see [this import](https://github.com/mitre-attack/tram/pull/61/commits/8f68e77ee0200860cd64f7395302fe172cd1466f#diff-0746836447d6aec88640ed0beff7b7e9d85354c9f503f4c622b1d239c1b3a21eR7) from data_svc.py and [this error check](https://github.com/mitre-attack/tram/pull/61/commits/8f68e77ee0200860cd64f7395302fe172cd1466f#diff-2f091ed9767d09b7f001fbee106277824202dc627ee567370c71624a97890a8dR124) whilst retrieving the models in ml_svc.py. For the latter, I would rename `tram/models/model_dict.p` (to something like 'old_model_dict.p') to re-trigger a build of the models. This is to avoid worrying about potential errors importing the existing models from that file as you would re-build a new one given your environment.

Finally, I would recommend using a virtual environment - not compulsory to make Tram run! Feel free to ignore if you already know: If you want to use Ubuntu, it can be risky editing the system-installed Python environment as something might break or not work (and Ubuntu uses Python). A virtual environment will be a Python environment which is separate to the one installed in your system. I usually whip one up quickly via opening a new project in PyCharm and selecting 'New environment using Virtualenv' (with /usr/bin/python3.9 as the base).

If you come across more errors whilst using Tram with your different dependency versions, feel free to say them here or in #69. Hope that helps!

**Comment by MarkDavidson** [comment]
Hello @Lex1020 and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and this issue is no longer present in that repository so I am closing this issue. Thank you!
