### ISSUE TITLE
Queue is ignored in-between sessions

### ISSUE THREAD

**Issue by jecarr** [mitre-attack/tram#88]
### **Please Describe The Problem To Be Solved**

Minor but the queue is currently being ignored in between sessions. My queue in TRAM may build up over time but only reports submitted in my current session will be completed (i.e. queue some reports, stop running TRAM, startup TRAM another time, queue is not resumed).

### *Proposed Change*

I have a fix here - arachne-threat-intel/thread@45f76bc - but haven't created a PR due to maintaining #61. The approach is to:
1. Prepare the queue before the app starts up (with any reports with status 'queue').
   a. Delete any related db items for this queued report as it will go through start_analysis() again and re-populate db
2. Allow the app to start up
3. Check queue which will trigger analysis of first report left in queue

**Comment by MarkDavidson** [comment]
Hello @jecarr and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and this issue is no longer present in that repository so I am closing this issue. Thank you!
