### ISSUE TITLE
Add CSV-file checks

### ISSUE THREAD

**Issue by jecarr** [mitre-attack/tram#89]
### **Please Describe The Problem To Be Solved**

Minor but the app currently allows any file to be selected for submitting bulk-reports.

### *Proposed Change*

I have fixes - see tagged - but haven't created a PR due to maintaining #61. The approach is to:
- Only allow .csv files to be selected (via the front-end)
  - https://github.com/arachne-threat-intel/thread/commit/533784a10deddf1564725d18c6e4b04085ecf1e8#diff-72c881cf01f09ddabbbc5d6162b06e77983ed34d3b4afd5156691a556a48e92a
- Also check via the server-side that the file can be parsed
  - arachne-threat-intel/thread@d8dfe6f

**Comment by MarkDavidson** [comment]
Hello @jecarr and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and this issue is no longer present in that repository so I am closing this issue. Thank you!
