### ISSUE TITLE
Punctuation in report titles breaks functionality

### ISSUE THREAD

**Issue by jecarr** [mitre-attack/tram#91]
### **Please Describe The Problem To Be Solved**

A user may submit titles with punctuation. This breaks some functionality in TRAM. For example:
- Test title with an apostrophe: 'I've done this report'; Attempt to export to pdf or navigator JSON:
  - Does not work; console states `Syntax error, expecting )`
  - This is because in columns.html, the buttons for the two export choices contain `<button onclick="$.getJSON('/export/pdf/{{file}}', ...` where **'** is used to enclose the string (hence making an apostrophe cause a syntax error)
- Test title with a ?: 'Will this work?'; Attempt to press 'Analyse' button on home page:
  - Does not work because when the url is parsed by the server-side, the trailing '?' is omitted.
  - This causes the report never to be retrieved (as this is done via title-matching).
  - This causes an IndexError in web_api.edit() when the line `sentences = await self.data_svc.get_report_sentences(report[0]['uid'])` is attempted (report[0] causing the IndexError)

### *Proposed Change*

I have fixes here - arachne-threat-intel/thread@5f02c5e & arachne-threat-intel/thread@1f6aa19 - but haven't created a PR due to maintaining #61.
- For the apostrophe-export issue, the approach is to favour the report-ID when making this request; other approaches may deem more suitable. (Edit: my opinion but I favoured the quote/unquote approach below so I applied that to this bug here Chockity-Pok/tram@46836c8)
- For the ? in an /edit/... url, the approach is to 'quote' and 'unquote' the report titles to ensure the punctuation is not omitted when searching the db using this title.
- Note: Slashes in a title (e.g. 'This/is/my title') will not get quoted and cause 404s: you can specify to quote the slashes via the `safe` parameter as seen here arachne-threat-intel/thread@a2b6ad3.

**Comment by MarkDavidson** [comment]
Hello @jecarr and thank you for the bug report. TRAM has moved to https://github.com/center-for-threat-informed-defense/tram and this issue is no longer present in that repository so I am closing this issue. Thank you!
